### ISSUE TITLE
Support rescript 11

### ISSUE THREAD

**Issue by salemkode** [TheSpyder/rescript-nodejs#18] opened 2023-08-12 10:38 UTC
![image](https://github.com/TheSpyder/rescript-nodejs/assets/58360393/57caec35-bb65-44ad-9b0a-3ef347930a35)

```zsh
FAILED: src/Module-NodeJs.cmj

  We've found a bug for you!
  /[[ project path ]]/node_modules/rescript-nodejs/src/Module.res:1:9-19

  1 │ include Node_module
  2 │ 

  The module or file Node_module can't be found.
  - If it's a third-party dependency:
    - Did you list it in bsconfig.json?
    - Did you run `rescript build` instead of `rescript build -with-deps`
      (latter builds third-parties)?
  - Did you include the file's directory in bsconfig.json?

rescript: [74/118] src/Buffer-NodeJs.cmj
FAILED: src/Buffer-NodeJs.cmj

  We've found a bug for you!
  /[[ project path  ]]/node_modules/rescript-nodejs/src/Buffer.res:1:10-20

  1 │ type t = Node.buffer
  2 │ open Js.TypedArray2
  3 │ 
```

**Comment by TheSpyder** [comment] 2023-08-12 10:46
What version are you on? v15 should've fixed this.

**Comment by TheSpyder** [comment] 2023-08-12 11:26
Duplicate of #15

**Closed** 2023-12-10 16:46 UTC
